apiVersion: v1
kind: Service

metadata:
  name: docker-nodejs-demo
  namespace: hvag-demo

spec:
  type: NodePort

  selector:
    app: docker-nodejs-demo

  ports:
  - port: 80
    protocol: TCP
    targetPort: nodejs-port

